#!/usr/bin/env bash

# TS
./node_modules/.bin/grpc_tools_node_protoc \
	--js_out=import_style=commonjs,binary:./src/api \
	--grpc_out=./src/api \
	--plugin=protoc-gen-grpc=./node_modules/.bin/grpc_tools_node_protoc_plugin \
	-I ./src/api \
	./src/api/*.proto

# JS
protoc \
	--plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
	--ts_out=./src/api \
	-I ./src/api \
	./src/api/*.proto
